language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g bower
  - bower install
before_script:
  - node_modules/gulp/bin/gulp.js build
  - node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --reporters dots
